services:
  converter:
    image: toolkit
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - ./rknn_api/rknn_api/:/src/
    ports:
      - 80:8000
    command: ["python", "src/app.py"]